core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

# App namespace
app_name = 'polls'


# URL pattern rules
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionDetail.as_view(), name='poll-detail'),
    path('<int:pk>/result/', views.result, name='poll-result'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Question(models.Model):
    """
    Abstracts a particular question
    """
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('Date Published')

    class Meta:
        ordering = ['-pub_date', 'question_text', ]

    def published_recently(self):
        """
        Check whether a Question was published within the last 5 hours
        Returns a boolean
        """
        now = timezone.now()
        return now - datetime.timedelta(hours=5) <= self.pub_date <= now

    def get_absolute_url(self, *args, **kwargs):
        return reverse('polls:question-detail', args=[str(self.pk)])

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    """
    Abstracts a Choice a particular question
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ['question', '-votes', ]

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from . import models


class PollForm(forms.ModelForm):
    class Meta:
        model = models.Choice
        fields = ('question', 'choice_text', )

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.utils import timezone

from . import models


class IndexView(generic.ListView):
    """
    List latest question
    """
    template_name = 'polls/index.html'
    model = models.Question

    def get_queryset(self, *args, **kwargs):
        return self.model.objects.filter(
            pub_date__lte=timezone.now()
        ).exclude(choice__isnull=True).order_by('-pub_date')[:5]


class QuestionDetail(generic.DetailView):
    model = models.Question
    template_name = 'polls/poll_detail.html'

    def get_queryset(self, *args, **kwargs):
        return self.model.objects.filter(
            pub_date__lte=timezone.now()
        ).exclude(choice__isnull=True)


def result(request, pk):
    """
    Display a particular question voting results
    """
    question = get_object_or_404(models.Question, pk=pk)
    template_name = 'polls/poll_result.html'
    return render(request, template_name, context={
        'question': question,
    })


def vote(request, pk):
    """
    Takecare voting of a particular poll
    """
    if request.method == 'POST':
        question = get_object_or_404(models.Question, pk=pk)

        try:
            selected_choice = question.choice_set.get(
                pk=request.POST['choice']
            )
        except:
            return render(
                request,
                'polls/poll_detail.html',
                context={
                    'error_message': 'You did not select any choice',
                    'question': question,
                }
            )
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('polls:poll-result', pk=pk)
    return render(request, 'polls/poll_detail.html')

polls/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}
  <title>Polling App</title>
  {% endblock title %}
  <meta name="viewport" content="widith=device-width, initial-scale=1.0">

  <!-- Vendor CSS -->
  <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">

  {% block vendor_css %}
  {% endblock vendor_css %}

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'assets/custom/css/default.css' %}">
  <link rel="stylesheet" href="{% static 'assets/custom/css/default.css' %}">

  {% block custom_css %}
  {% endblock custom_css %}
</head>
<body>
  {% block page_wrapper %}
  <div id="page_wrapper">

    <!-- page header -->
    <header id="pageHeader">
      <div class="container-fluid">
        <a href="{% url 'polls:index' %}">
          <i class="fa fa-home"></i> Home
        </a>
      </div>
    </header>
    
    <!-- Page Main -->
    {% block page_main %}
    {% endblock page_main %}

  </div><!-- /#page_wrapper -->
  {% endblock page_wrapper %}

<!-- Vendor JavaScript -->
<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery/bootstrap.min.js' %}"></script>

{% block vendor_js %}
{% endblock vendor_js %}

<!-- Custom JavaScript -->
<script src="{% static 'assets/custom/js/script.js' %}"></script>

{% block custom_js %}
{% endblock custom_js %}
</body>
</html>

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block page_main %}
<div class="container-fluid">
    <h1>POLLING APP</h1>

    <h4>Questions</h4>
    <ul class="list-unstyled">
      {% for question in question_list %}
      <li>
        <a href="{% url 'polls:poll-detail' question.id %}">{{ forloop.counter }}. {{ question.question_text }}</a>
      </li>
      {% empty %}
      <p>No polls are available</p>
      {% endfor %}
    </ul>
</div>
{% endblock page_main %}

polls/templates/polls/poll_detail.html
{% extends 'base.html' %}

{% block page_main %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ question.question_text }}</h2>

            {% if error_message %}
            <p>{{ error_message }}</p>
            {% endif %}
            
            <form name="poll_form" action="{% url 'polls:vote' question.id %}" method="POST">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                  <label class="radio">
                      <input type="radio" name="choice" value="{{ choice.id }}"> 
                      {{ choice.choice_text }}
                  </label>
                {% endfor %}

                <div class="form-group">
                    <button type="submit" class="btn btn-default">Vote</button>
                </div>
            </form>
        </div>
    </div>
    
</div>
{% endblock page_main %}

polls/templates/polls/poll_result.html
{% extends 'base.html' %}

{% block page_main %}
<div class="container-fluid">
    <h2>{{ question.question_text }}</h2>
    <h4>Results</h4>

    {% if question.choice_set.all %}
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} &nbsp; - &nbsp; ({{ choice.votes }} votes)</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}